In [40]:
import numpy as np
from numpy import linalg

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [15]:
N = 10
arr = np.arange(start = N - 1, stop = -1, step = -1)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [37]:
#v1
arr_1 = np.eye(N)
print(arr_1 * arr, (arr_1 * arr).sum())
#v2
matrix_2 = np.diag(arr, k=0)
print(matrix_2, matrix_2.sum())

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 45.0
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]] 45


Задание 3
Решите систему уравнений:
4x + 2y + z = 4-----
x + 3y = 12-----
5y + 4z = -3

In [49]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

solve_ = linalg.solve(a, b) # решили систему линейных уравнений
calculation_ = np.dot(a, solve_)
print(solve_, calculation_, np.allclose(calculation_, b))#проверили решение методом поэлементного сравнения

[ 0.46666667  3.84444444 -5.55555556] [ 4. 12. -3.] True


Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя(№ строки + 1). Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель, о покупках которого известно следующее: next_user_stats.
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.

In [53]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

array([2, 1, 0, 0, 0, 0])

In [61]:
cos_metric_max = 0
user_ID = 0
for uid, item in enumerate(users_stats):
    cos_metric = np.dot(item, next_user_stats) / ((np.linalg.norm(item) * np.linalg.norm(next_user_stats)))
    if cos_metric_max < cos_metric:
        cos_metric_max = cos_metric
        user_ID = uid + 1

print(f'Наибольшее сходство с пользователем "{user_ID}" с косинусной метрикой {cos_metric_max}')
        

Наибольшее сходство с пользователем "8" с косинусной метрикой 0.9486832980505138


In [64]:
dict_ = {}
dict_ = {uid+1:np.dot(item, next_user_stats)/((np.linalg.norm(item)*np.linalg.norm(next_user_stats))) for uid, item in enumerate(users_stats)}
dict_.max()

AttributeError: 'dict' object has no attribute 'max'

{1: 0.19999999999999996,
 2: 0.8451542547285165,
 3: 0.3999999999999999,
 4: 0.7905694150420948,
 5: 0.3999999999999999,
 6: 0.0,
 7: 0.0,
 8: 0.9486832980505138,
 9: 0.0,
 10: 0.0}